#base "../../../../cfg/hexhud/hex_specgui_stream.txt"
#base "../../../../cfg/hexhud/hex_spectator_res.txt"
#base "../../../../cfg/hexhud/hex_spectator_bars.txt"
#base "hudinspectpanel.res"
#base "spectatortournament_hex.res"